services:

  api:
    build: .
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petdb
    depends_on:
      - consul-client
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    network_mode: "service:consul-client" # Use consul-client's network stack

  consul-client:
      image: hashicorp/consul:1.21
      hostname: api-server-01
      restart: always
      volumes:
        - ./consul/:/etc/consul.d/config/:ro
        - ./consul/tmp-data/cli:/opt/consul/data
      command: "consul agent -config-dir=/etc/consul.d/config/"
      networks:
        consul-servers_consul-nw:
          ipv4_address: 10.100.10.20

networks:
  consul-servers_consul-nw:
    external: true