services:

  api:
    build: .
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petdb
      POSTGRES_HOST: db
    depends_on:
      - consul-client
    network_mode: "service:consul-client" # Use consul-client's network stack

  consul-client:
      image: hashicorp/consul:1.21
      hostname: api-server-01
      restart: always
      volumes:
        - ./consul/:/etc/consul.d/config/:ro
        - ./consul/tmp-data/cli:/opt/consul/data
      command: "consul agent -config-dir=/etc/consul.d/config/"
      networks:
        consul-servers_consul-nw:
          ipv4_address: 10.100.10.20

networks:
  consul-servers_consul-nw:
    external: true